# Generated by Django 5.1.6 on 2025-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='completion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='not_started', max_length=15),
        ),
    ]
