# Generated by Django 5.1.6 on 2025-02-25 20:56

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapplication_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.job_completion_upload_path),
        ),
    ]
